(function(){
const coreset=[

{id:"homepage",
	attr:"#tipitaka#buddha#dhamma#sangha#patimokkha#mnemonic#dn#mn"
	,zh:"首頁",en:"homepage",pli:"-"
},
{id:"patimokkha",zh:"巴帝摩卡",pli:"paṭimokkha"},
{id:"editing",zh:"編輯中",en:"editing",content:"#mn",en:"-",pli:"-"},
{id:"buddha",zh:"佛",en:"Buddha",pli:"buddha"},
{id:"dhamma",
	en:"dhamma",
	zh:"法",
	types:"#4ariyasacca#paticcasamuppada#24paccayo#paramattha",
	pli:"dhamma"
},
{id:"sangha",zh:"僧",en:"Sangha",pli:"saṅgha"},
{id:"mnemonic",zh:"口訣",en:"mnemonic",pli:"-"},
{id:"2sangha",zh:"二種僧"
	,has:"#sammutisangha#ariyasangha"
	,classification:"#sangha"},
{id:"sammutisangha",zh:"世俗僧伽",has:"#sammuti",pli:"sammuti"},
{id:"ariyasangha",zh:"聖者僧伽",has:"#ariya",en:"noble sangha",pli:"ariya"},
{id:"nibbana",zh:"涅槃",en:"enlightenment",pli:"nibbana"},

{id:"samadhi",zh:"定|三昧|三摩地|等持",en:"concentration",pli:"samādhi"},
{id:"samapatti",zh:"等至",en:"attainment",pli:"samāpatti"},
{id:"anapanasati",zh:"入出息念",en:"mindfullness of breathing",pli:"ānāpānasati"},
{id:"samatha",zh:"止|奢摩他",en:"serenity",pli:"samatha"},
{id:"vipassana",zh:"觀",en:"insight",pli:"vipassana"},
{id:"kasina",zh:"遍相",en:"kasina",pli:"ānāpānasati"},
{id:"loka",zh:"世間",en:"mundane",pli:"loka",types:"#kamaloka#rupaloka#arupavacara"},
{id:"37maggavagga",zh:"37道品",has:"#4satipatthana#4sammappadhana#4iddhipada#5indriya#5bala#7bojjhanga#8magganga",pli:"maggavagga"},
{id:"4satipatthana",zh:"四念住",has:"#kaya#vedana#citta#dhamma",en:"for foundation of mindfullness",pli:"cattaro satipaṭṭhāna"},
{id:"4sammappadhana",zh:"四正勤",def:"一斷除已生的惡法；二防止未生的惡法起；三令未生的善法生起；四令已生的善法增長。",en:"four supreme efforts",pli:"sammappadhāna"},

{id:"4iddhipada",zh:"四神足|成就之法",has:"#chanda#viriya#citta#vimamsa",en:"four means to accomplishment",pli:"iddhipāda"},

{id:"vimamsa",zh:"觀察|實驗調查",en:"investigation",pli:"vīmaṃsā"},


{id:"5indriya",zh:"五根",has:"#saddha#viriya#sati#samadhi#panna",en:"five faculties",pli:"indriya"},
{id:"5bala",zh:"五力",has:"#saddha#viriya#sati#samadhi#panna",en:"five powers",pli:"bala"},
{id:"7bojjhanga",zh:"七覺支",has:"#sati#dhammavicaya#viriya#piti#passaddhi#samadhi#upekkhanga",en:"seven factors of enlightment",pli:"satta bojjhangā"},
{id:"dhammavicaya",zh:"擇法",en:"investigation of states",pli:"dhammavicaya",syn:"#panna"},
{id:"upekkhanga",zh:"捨覺分",syn:"#tatramajjhattata",def:"指中捨性，非捨受。概要精解pg272",en:"equanimity",pli:"-"},
{id:"8magganga",zh:"八道分",has:"#sammaditthi#sammasankappo#sammavaca#sammakammanta#sammaajiva#sammavayamo#sammasati#sammasamadhi",en:"eight fold path",pli:"aṭṭhamaggaṅga"},
{id:"sammaditthi",zh:"正見",en:"right view",pli:"sammādiṭṭhi",stem:"#ditthi"},
{id:"sammasankappo",zh:"正思惟",def:"導向#nekkhamma; #adosa; #alobha; 的#vitakka;",en:"right intention",pli:"sammasaṅkappo"},
{id:"sammakammanta",zh:"正業",en:"right action",pli:"sammākammanta"},
{id:"sammaajiva",zh:"正命",en:"right livelihood",pli:"sammāājīva"},
{id:"sammavayamo",zh:"正精進",syn:"#4sammappadhana",en:"right effort",pli:"sammāvāyāmo"},
{id:"sammasati",zh:"正念",syn:"#4satipatthana", en:"right mindfullness",pli:"sammasati",stem:"#sati"},
{id:"sammasamadhi",zh:"正定",def:"依長部22經定義為#suttanta4jhana;",en:"right concentration",pli:"sammāsamādhi",stem:"#samadhi"},

{id:"lokiyacitta",zh:"世間心",en:"mundane consciousness",pli:"lokiyacitta",stem:"#loka"},

{id:"lokuttara",zh:"出世間",anto:"#loka",syn:"#nibbana",en:"supermundane",pli:"lokuttara"},
{id:"ariya",zh:"聖者",en:"noble one",pli:"ariya",attr:"#nibbana#phala",has:"#sotapanna#sakadagami#anagami#arahant"},
{id:"sotapanna",title:"須陀洹",zh:"須陀洹|預流果",en:"stream-entry",pli:"sotāpanna"},
{id:"sakadagami",zh:"斯陀含|一來果",en:"once-returner",pli:"sakadāgāmi"},
{id:"anagami",zh:"阿那含|不還果",en:"no-returner",pli:"anāgāmi"},
{id:"arahant",zh:"阿羅漢|阿拉汉",en:"arahant",pli:"arahant"},
{id:"4ariyasacca",zh:"四聖諦",has:"#dukkhasacca#samudayasacca#nirodhasacca#maggasacca",en:"4 noble truth",pli:"cattāro ariyasacca"},
{id:"2sacca",zh:"二諦",has:"#sammutisacca#paramatthasacca",pli:"dvesaccāni"},
{id:"sammuti",zh:"世俗",pli:"sammuti"},
{id:"sammutisacca",zh:"世俗諦",stem:"#sammuti",has:"#sammuti#pannatti#vohara",pli:"sammutisacca"},
{id:"sukha",zh:"樂",is:"#vedana",en:"happiness",pli:"sukha"},
{id:"dukkha",zh:"苦",is:"#vedana",en:"suffering",pli:"dukkha"},
{id:"samudaya",zh:"集",en:"origination",pli:"samudaya"},
{id:"nirodha",zh:"滅",en:"cessation",pli:"nirodha"},
{id:"magga",zh:"道",en:"path",pli:"magga"},
{id:"phala",zh:"果",en:"fruition",pli:"phala"},
{id:"anicca",zh:"無常",en:"impermanence",pli:"anicca"},
{id:"atta",zh:"有我",en:"self",pli:"atta"},
{id:"anatta",zh:"無我",anto:"#atta",en:"non-self",pli:"anatta"},
{id:"dukkhasacca",stem:"#dukkha",zh:"苦諦",en:"the truth of suffering",pli:"dukkhasacca"},
{id:"samudayasacca",stem:"#samudaya",zh:"集諦",en:"the truth of origination",pli:"samudayasacca"},
{id:"nirodhasacca",stem:"#nirodha",zh:"滅諦",en:"the truth of cessation",pli:"nirodhasacca"},
{id:"maggasacca",stem:"#magga",zh:"道諦",en:"the truth of the Path",pli:"maggasacca",has:"#37maggavagga"},

{id:"pannatti",zh:"概念",en:"concept",pli:"paññātti"},
{id:"vohara",zh:"表達方式",pli:"vohara"},
{id:"paramatthasacca",zh:"究竟諦",en:"ultimate truth",pli:"parāmaṭṭha sacca",
has:"#paramattha"},
{id:"3ratana",zh:"三寶",	en:"triple Gem",pli:"Tiratana",has:"#buddha#dhamma#sangha"},
{id:"paramattha",zh:"究竟法",en:"ultimate reality",pli:"paramatta",	has:"#lakkhana#rasa#paccupatthana#padatthana",stem:"#parama#attha",source:"《概要精解》p4"
},
{id:"indriya",zh:"根",def:"覺知的能力",en:"faculty",pli:"indriya"},
{id:"lakkhana",zh:"相",en:"characteristic",pli:"lakkhaṇa"},
{id:"rasa",zh:"作用",amb:"#rasa",en:"function",pli:"rasa"},
{id:"paccupatthana",zh:"現起",en:"manifestation", pli:"paccupaṭṭhāna"},
{id:"padatthana",zh:"近因|足處",en:"proximate cause", pli:"padaṭṭhāna"},
{id:"parama",zh:"勝義",en:"ultimate",pli:"parama"},
{id:"attha",zh:"道理",pli:"attha"},
{id:"4paramattha",	zh:"四究竟法",classification:"#paramattha",	has:"#rupa#citta#cetasika#nibbana",en:"-",pli:"-"},
{id:"5khanda",zh:"五蘊",	pli:"pañcakhaṇḍa",en:"five aggregates",
	has:"#rupa#vedana#sanna#sankhara#vinnana",    is:"#paramattha"},
{id:"vedana",zh:"受",en:"feeling",pli:"vedanā"},
{id:"sanna",zh:"想",en:"perception",pli:"saññā"},
{id:"sankhara",zh:"行",en:"mental formation",pli:"saṅkhāra"},
{id:"vinnana",zh:"識",types:"#vinnanadhatu",en:"consciousness",pli:"viññāṇa"},

{id:"dvadasayatana",zh:"十二處",has:"#cakkhu#sota#ghana#jivha#kaya#manayatana#rupayatana#saddha#gandha#rasarammana#photthabba#dhammayatana",en:"twelve sense bases",pli:"dvādasāyatana"},
{id:"rupayatana",zh:"色處",en:"visible form base",pli:"rūpāyatana"},
{id:"manayatana",zh:"意處",def:"含所有 89種#citta;",en:"mind base",pli:"manāyatana"},
{id:"dhammayatana",zh:"法處",has:"#cetasika#sukhuarupa#nibbana",en:"mental object base",pli:"dhammāyatana"},

{id:"sukhuarupa",zh:"微細色",def:"16種，概要精解pg284",en:"subtle material phenomena",pli:"sukhumarūpa"},

{id:"18dhatu",zh:"18界",def:"將#dvadasayatana;中的#manayatana;分為#vinnanadhatu;，即得十八處。",en:"eighteen elements",pli:"aṭṭhārasadhātu"},

{id:"mano",zh:"意",en:"mind",pli:"mana"},
{id:"citta",zh:"心",en:"mind",pli:"citta",lakkhana:"vijanana",	rasa:"pubbangama",	paccupatthana:"sandhana",	padatthana:"#namarupa"
,classification:"#catubbhidhacitta",def:"1)作為造作者，心是識知目標者（ ārammaṇaṁ cintetī ti cittaṁ, 2)作為工具，與心相應的心所通過心而得以識知目標（etena cintentī ti cittam）3)作為活動，心純粹只是識知的過程（cintanamattaṁ cittaṁ）。"},
{id:"catubbhidhacitta",zh:"四種心",has:"#kamavacaracitta#rupavacaracitta#arupavacaracitta#lokuttaracitta",en:"4 types of consciousness",pli:"catubbhidha citta"},
{id:"kamavacaracitta",zh:"欲界心",stem:"#kamavacara",en:"sense-sphere consciousness",pli:"kāmāvacara citta",types:"#12akusakacitta#18ahetukacitta#24kamavacarasobhanacitta",def:"共54個"},
{id:"rupavacaracitta",zh:"15色界心",is:"#mahaggatacitta",stem:"#rupavacara",en:"fine-material consciousness",pli:"rūpāvacara citta",has:"#5rupavacarakusalacitta#5rupavacaravipakacitta#5rupavacarakiriyacitta"},
{id:"5rupavacarakusalacitta",zh:"5色界善心",func:"#javana",stem:"#kusalacitta",has:"#pathamajhana#dutiyajjhana#tatiyajjhana#catuttajjhana#pancamajjhana",en:"sense-sphere wholesome consciousness",pli:"rūpāvacara kusalacitta"},

{id:"pathamajhana",zh:"第一禪",is:"5jhana",syn:"#1jhana",en:"first jhana",pli:"paṭhamajhāna",has:"#vitakka#vicara#piti#sukha#ekaggata"},
{id:"dutiyajjhana",zh:"第二禪",is:"5jhana",syn:"#2jhana",en:"second jhana",pli:"dutiyajjhāna",has:"#vicara#piti#sukha#ekaggata"},
{id:"tatiyajjhana",zh:"第三禪",is:"5jhana",syn:"#2jhana",en:"third jhana",pli:"tatiyajjhāna",has:"#piti#sukha#ekaggata"},
{id:"catuttajjhana",zh:"第四禪",is:"5jhana",syn:"#3jhana",en:"fourth jhana",pli:"catuttajjhāna",has:"#sukha#ekaggata"},
{id:"pancamajjhana",zh:"第五禪",is:"5jhana",syn:"#4jhana",en:"fifth jhana",pli:"pancamajjhāna",has:"#upekkha#ekaggata"},

{id:"jhana",zh:"禪那",en:"absorption",pli:"jhāna",types:"#suttanta4jhana#5jhana"},
{id:"5jhana",zh:"五分禪那",content:"savitakka savicāra samādhi; avitakka vicaramatta samādhi; avitakka avicāra samādhi: M.128/iii,162）。尋伺兩者相應之定、尋不相應伺相應之定、尋伺兩者皆不相應之定。概要精解pg43",has:"#vitakka#vicara#piti#sukha#ekaggata",en:"five jhana",pli:"pañca jhāna"},
{id:"suttanta4jhana",zh:"經教四禪",has:"#1jhana#2jhana#3jhana#4jhana",en:"four jhana in suttanta system",pli:"-"},
{id:"1jhana",zh:"初禪",en:"first jhana",pli:"paṭhamajhāna"},
{id:"2jhana",zh:"二禪",has:"#piti#sukha#ekaggata",en:"second jhana",pli:"dutiyajjhāna"},
{id:"3jhana",zh:"三禪",has:"#sukha#ekaggata",en:"third jhana",pli:"tatiyajjhāna"},
{id:"4jhana",zh:"四禪",has:"#upekkha#ekaggata",en:"fourth jhana",pli:"catuttajjhāna"},

{id:"5rupavacaravipakacitta",zh:"5色界果報心",function:"#patisandhi",stem:"#vipakacitta",has:"#pathamajhana#dutiyajjhana#tatiyajjhana#catuttajjhana#pancamajjhana",en:"sense-sphere resultant consciousness",pli:"rūpāvacara vipakacitta"},
{id:"5rupavacarakiriyacitta",zh:"5色界唯作心",func:"#javana",stem:"#kiriyacitta",has:"#pathamajhana#dutiyajjhana#tatiyajjhana#catuttajjhana#pancamajjhana",en:"sense-sphere functional consciousness",pli:"rūpāvacara kiriyacitta"},

{id:"arupavacaracitta",zh:"12無色界心",is:"#mahaggatacitta",has:"#4arupavacarakusalacitta#4arupavacaravipakacitta#4arupavacarakiriyacitta", stem:"#arupavacara",en:"immaterial consciousness",pli:"arūpāvacara citta"},
{id:"4arupavacarakusalacitta",zh:"4無色界善心",func:"#javana",has:"#akasanancayatanacitta#vinnanancayatanacitta#akincannayatanacitta#nevasannanasannayatanacitta",stem:"#arupavacara#kusalacitta",en:"immaterial wholesome consciousness",pli:"arūpāvacarakusalacitta"},
{id:"4arupavacaravipakacitta",zh:"4無色界果報心",function:"#patisandhi",has:"#akasanancayatanacitta#vinnanancayatanacitta#akincannayatanacitta#nevasannanasannayatanacitta",stem:"#arupavacara#vipakacitta",en:"immaterial resultant consciousness",pli:"arūpāvacaravipākacitta"},
{id:"4arupavacarakiriyacitta",zh:"4無色界唯作心",func:"#javana",has:"#akasanancayatanacitta#vinnanancayatanacitta#akincannayatanacitta#nevasannanasannayatanacitta",stem:"#arupavacara#kiriyacitta",en:"immaterial funcional consciousness",pli:"arupavacarakiriyacitta"},

{id:"mahaggatacitta",zh:"廣大心",en:"sublime,lofty or exalted consciousness",pli:"mahaggatacitta"},
{id:"akasananca",zh:"空無邊",stem:"akasa",en:"boundless space",pli:"ākāsānañca"},

{id:"akincanna",zh:"無所有",en:"nothingness",pli:"ākincaññā"},
{id:"akasanancayatanacitta",zh:"空無邊處心",arm:" #akasanancayatana;的#pannatti;",def:"超越#kasina;的#pannatti;",en:"consciousness pertaining to the base of infinite space|boundless space",pli:"ākasānañcāyatanacitta"},
{id:"vinnanancayatanacitta",zh:"識無邊處心",arm:"#akasanancayatanacitta",def:"超越#akasananca;的#pannatti;",en:"consciousness pertaining to the base of boundless consciousness|boundless consciousness",pli:"viññāṇañcāyatanacitta"},
{id:"akincannayatanacitta",zh:"無所有處心",arm:" #akasananca;的#pannatti;",def:"超越#vinnanancayatanacitta;",en:"consciousness pertaining to the base of nothingness",pli:"ākincaññāyatanacitta"},
{id:"nevasannanasannayatanacitta",zh:"非想非非想處心",arm:"#akincannayatanacitta",def:" 超越#akincanna;的#pannatti;",en:"consciousness pertaining to the base of neither perception nor non-perception",pli:"n'evasaññān'āsaññāyatanacitta"},

{id:"akasanancayatana",zh:"空無邊處",en:"base of infinite space|boundless space",pli:"ākasānañcāyatana"},
{id:"vinnanancayatana",zh:"識無邊處",en:"base of boundless consciousness|boundless consciousness",pli:"viññāṇañcāyatana"},
{id:"akincannayatana",zh:"無所有處",en:"base of nothingness",pli:"ākincaññāyatana"},
{id:"nevasannanasannayatana",zh:"非想非非想處",en:"base of neither perception nor non-perception",pli:"n'evasaññān'āsaññāyatana"},

{id:"lokuttaracitta",zh:"8出世間心",arm:"#nibbana",func:"#javana",stem:"#lokuttara",en:"supermundane consciousness",pli:"lokuttaracitta",has:"#4lokuttarakusalacitta#4lokuttaravipakacitta"},
{id:"4lokuttarakusalacitta",zh:"4出世間善心",stem:"#kusalacitta",has:"#sotapattimaggacitta#sakadagamimaggacitta#anagamimaggacitta#arahattamaggacitta",en:"supermundane wholesome consciousness",pli:"lokuttarakusalacitta"},
{id:"4lokuttaravipakacitta",zh:"4出世間果報心",stem:"#vipakacitta",has:"#sotapattiphalacitta#sakadagamiphalacitta#anagamiphalacitta#arahattaphalacitta",en:"supermundane resultant consciousness",pli:"lokuttaravipākacitta"},

{id:"sotapattimaggacitta",zh:"須陀洹道心",is:"#maggacitta",en:"path consciousness of stream-entry",pli:"sotāpattimaggacitta",stem:"#sotapanna"},
{id:"sakadagamimaggacitta",zh:"斯陀含道心",is:"#maggacitta",en:"path consciousness of once-returning",pli:"sakadāgāmimaggacitta",stem:"#sakadagami"},
{id:"anagamimaggacitta",zh:"阿那含道心",is:"#maggacitta",en:"path consciousness of no-returning",pli:"anāgāmimaggacitta",stem:"#anagami"},
{id:"arahattamaggacitta",zh:"阿羅漢道心",is:"#maggacitta",en:"path consciousness of arahantship",pli:"arahattamaggacitta",stem:"#arahant"},

{id:"sotapattiphalacitta",zh:"須陀洹果心",is:"#phalacitta",en:"fruition consciousness of stream-entry",pli:"sotāpattiphalacitta",stem:"#sotapanna"},
{id:"sakadagamiphalacitta",zh:"斯陀含果心",is:"#phalacitta",en:"fruition  consciousness of once-returning",pli:"sakadāgāmiphalacitta",stem:"#sakadagami"},
{id:"anagamiphalacitta",zh:"阿那含果心",is:"#phalacitta",en:"fruition consciousness of no-returning",pli:"anāgāmiphalacitta",stem:"#anagami"},
{id:"arahattaphalacitta",zh:"阿羅漢果心",is:"#phalacitta",en:"fruition consciousness of arahantship",pli:"arahattaphalacitta",stem:"#arahant"},

{id:"maggacitta",zh:"道心",en:"path consciousness",pli:"maggacitta"},
{id:"phalacitta",zh:"果心",en:"fruition consciousness",pli:"phalacitta"},


{id:"magganana",zh:"道智",en:"path knowledge",pli:"maggañāṇa"},
{id:"phalanana",zh:"果智",en:"fruition knowledge",pli:"phalañāṇa"},
{id:"phalasamapatti",zh:"果定|果等至",is:"#samapatti",stem:"#phala",en:"fruition attainment",pli:"phalasamāpatti"},
{id:"kusala",zh:"善",en:"wholesome",pli:"kusala"},
{id:"akusala",zh:"不善",en:"unwholesome",pli:"akusala"},
{id:"12akusakacitta",zh:"12不善心",func:"#javana",en:"12 unwholesome",pli:"akusalacitta",has:"#8lobhamulacitta#2dosamulacitta#2mohamulacitta"},
{id:"8lobhamulacitta",zh:"8貪根心",en:"12 greed-rooted",pli:"lobha mūla citta",or1:"#somanassasahagata#domanassasahagata",or2:"#ditthigatasampayutta#ditthigatavippayutta",or3:"#sasankharika#asankharika",stem:"#lobha"},
{id:"somanassasahagata",zh:"悅俱" ,en:"accompanied by joy",pli:"somanassasahagata",stem:"#somanassa"},
{id:"domanassasahagata",zh:"憂俱" ,en:"accompanied by displeasure",pli:"somanassasahagata",stem:"#domanassa"},
{id:"upekkhasahagata",zh:"捨俱",stem:"#upekkha" ,en:"accompanied by equanimity",pli:"upekkhāsahagata"},
{id:"ditthigatasampayutta",zh:"邪見相應",en:"associated with wrong view",pli:"diṭṭhigatasampayutta",stem:"#ditthi#sampayutta"},
{id:"ditthigatavippayutta",zh:"邪見不相應",en:"dissociated with wrong view",pli:"diṭṭhigatavippayutta",stem:"#ditthi#vippayutta"},
{id:"sasankharika",zh:"有行",amb:"#sankhara",def:"受到慫恿",en:"prompted",pli:"sasaṅkhārika"},
{id:"asankharika",zh:"無行",amb:"#sankhara",def:"沒有受到慫恿",en:"unprompted",pli:"asaṅkhārika"},
{id:"5akusalasasankharikacitta",zh:"5不善有行心",def:"即#8lobhamulacitta;中的四個及#2dosamulacitta;中的一個",en:"5 unwholesome prompted consciousness",pli:"akusalasasaṅkhārikacitta"},
{id:"2dosamulacitta",zh:"2瞋根心",en:"2 hatred-rooted",stem:"#dosa", attr:"#domanassasahagata#patighasampayutta",or:"#sasankharika#asankharika",pli:"dosa mūla citta"},
{id:"patighasampayutta",zh:"瞋恚相應",en:"associated with hatred",pli:"paṭighasampayutta",stem:"#patigha#sampayutta"},
{id:"patigha",zh:"瞋恚",syn:"#dosa",en:"aversion",pli:"paṭigha"},
{id:"2mohamulacitta",zh:"2痴根心",attr:"#upekkhasahagata", stem:"#moha", en:"2 delusion-rooted",pli:"mohamūlacitta",or:"#vicikicchasampayutta#uddhaccasampayutta"},
{id:"vicikicchasampayutta",zh:"疑相應",en:"associated with doubt",pli:"vicikicchāsampayutta",stem:"#vicikiccha"},
{id:"uddhaccasampayutta",zh:"掉舉相應",en:"associated with restlessness",pli:"uddhaccasampayutta",stem:"#uddhacca"},
{id:"18ahetukacitta",attr:"#ahetuka",zh:"18無因心",en:"18 rootless",pli:"ahetukacitta",has:"#7akusalavipakacitta#8kusalavipakahetukacitta#3ahetukakiriyacitta"},
{id:"sahetuka",zh:"有因",en:"with root",pli:"sahetuka"},
{id:"ahetuka",zh:"無因",en:"rootless",pli:"ahetuka"},
{id:"7akusalavipakacitta",zh:"7不善果報心",en:"7 unwholesome resultant",pli:"akusala vipāka",def:"因#anittha;所緣生起。「#akusala;」一詞並非形容這些心本身，而是形容產生它們的#kamma;。概要精解pg20 一切不善果報心皆是#ahetuka;。",has:"#cakkhuvinnana#sotavinnana#ghanavinnana#jivhavinnana#dukkhasahagatakayavinnana#sampaticchanacitta#upekkhasahagatasantiranacitta",is:"#vipakacitta"},
{id:"dvipancavinnana",zh:"雙五識",en:"five sensuous consciousness",pli:"dvipañcaviññāṇa",has:"#cakkhuvinnana#sotavinnana#ghanavinnana#jivhavinnana#kayavinnana",with:"#7sabbacittasadharana"},
{id:"cakkhuvinnana",zh:"眼識",attr:"#upekkhasahagata",base:"#cakkhupasada",en:"eye consciousness",pli:"cakkhuviññaṇa"},
{id:"sotavinnana",zh:"耳識",attr:"#upekkhasahagata",base:"#sotapasada",en:"ear consciousness",pli:"sotaviññaṇa"},
{id:"ghanavinnana",zh:"鼻識",attr:"#upekkhasahagata",base:"#ghanapasada",en:"nose consciousness",pli:"ghānaviññaṇa"},
{id:"jivhavinnana",zh:"舌識",attr:"#upekkhasahagata",base:"#jivhapasada",en:"tongue consciousness",pli:"jivhāviññaṇa"},
{id:"kayavinnana",zh:"身識",base:"#kayapasada",en:"body consciousness",pli:"kāyaviññaṇa",stem:"#kayavinnana"},
{id:"dukkhasahagatakayavinnana",zh:"苦俱身識",attr:"dukkhasahagata",en:"body consciousness accompanied by pain",pli:"kāyaviññaṇa",stem:"#kayavinnana"},
{id:"sukkhasahagatakayavinnana",zh:"樂俱身識",attr:"sukkhasahagata",en:"body consciousness accompanied by joy",pli:"kāyaviññaṇa",stem:"#kayavinnana"},
{id:"sampaticchanacitta",attr:"#upekkhasahagata",zh:"領受心",or:"#kusalavipaka#akusalavipaka",en:"receiving consciousness",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha",pli:"sampaṭicchanacitta"},
{id:"santiranacitta",zh:"推度心",en:"investigating consciousness",pli:"santiraṇacitta"},
{id:"santirana",zh:"推度",en:"investigation",pli:"santiraṇa"},
{id:"upekkhasahagatasantiranacitta",or:"#kusalavipaka#akusalavipaka",attr:"#upekkhasahagata",zh:"捨俱推度心",func:"#patisandhi#tadarammana#santirana",en:"investigating consciousness",pli:"santiraṇacitta",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha",stem:"#santirana"},
{id:"somanasasahagatasantiranacitta",attr:"#somanassasahagata", zh:"悅俱推度心",func:"#tadarammana#santirana",en:"investigating consciousness",pli:"santiraṇacitta",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha#piti",stem:"#santirana"},
{id:"8kusalavipakahetukacitta",attr:"#ahetuka",stem:"#kusala#vipakacitta",zh:"8善果報無因心",en:"8 wholesome rootless resultant",pli:"kusala vipāka",has:"#cakkhuvinnana#sotavinnana#ghanavinnana#jivhavinnana#sukkhasahagatakayavinnana#sampaticchanacitta#somanasasahagatasantiranacitta#upekkhasahagatasantiranacitta",def:"因#ittha;所緣及#atiittha;所緣生起",is:"#vipakacitta"},

{id:"ittha",zh:"可喜",en:"desirable",pli:"iṭṭha"},
{id:"anittha",zh:"不可喜",en:"undesirable",pli:"aniṭṭha"},
{id:"atiittha",zh:"極可喜",en:"extremely desirable",pli:"ati iṭṭha"},
{id:"3ahetukakiriyacitta",zh:"3無因唯作心",en:"3 rootless functional",pli:"ahetukakiriya",has:"#pancadvaravajjanacitta#manodvaravajjanacitta#hasituppadacitta"},
{id:"pancadvaravajjanacitta",is:"#kiriyacitta",attr:"#upekkhasahagata",zh:"五門轉向心",en:"five door adverting consciousness",pli:"pañcadvārājjanacitta",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha"},
{id:"3manodhatu",zh:"3意界",has:"#pancadvaravajjanacitta#sampaticchanacitta",en:"mind element",pli:"manodhātu",def:"只是非常粗淺地識知目標"},
{id:"vinnanadhatu",zh:"7識界",has:"#cakkhuvinnana#sotavinnana#ghanavinnana#jivhavinnana#kayavinnana#3manodhatu#manovinnanadhatu",en:"seven consciousness elements",pli:"viññāṇadhātu"},
{id:"manovinnanadhatu",zh:"76意識界",def:"除去 #dvipancavinnana;及#3manodhatu;的所有心 89-10-3=76。能更完整與清晰地識知目標，因為在它們前後的心都擁有相同的目標",en:"mind consciousness element",pli:"manoviññāṇadhātu"},
{id:"manodvaravajjanacitta",is:"#kiriyacitta",attr:"#upekkhasahagata",zh:"意門轉向心",en:"mind door adverting consciousness",pli:"manodvarāvājjanacitta",syn:"#votthapanacitta"},
{id:"votthapanacitta",zh:"確定心",en:"determining consciousness",pli:"votthapanacitta",def:"當#manodvaravajjanacitta;出現在#pancadvaravithi;時稱為確定心",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha#viriya"},
{id:"hasituppada",zh:"生笑",def:"凡夫經由 4悅俱貪根+4悅俱大善心生笑，有學聖者前面8個除去邪見相應2個，共6個心可生笑，#arahantsmile;",en:"smile",pli:"hasituppāda"},
{id:"hasituppadacitta",is:"#kiriyacitta",attr:"#somanassasahagata",zh:"生笑心",func:"#javana",en:"smile producing",pli:"hasituppādacitta",with:"#7sabbacittasadharana#vitakka#vicara#adhimokkha#viriya#piti"},

{id:"kiriya",zh:"唯作",en:"functional",pli:"kiriya"},
{id:"kusalacitta",zh:"善心",en:"wholesome consciousness",pli:"kusalacitta"},
{id:"kusalavipaka",zh:"善果報心",en:"wholesome resultant",pli:"kusalavipāka"},
{id:"akusalavipaka",zh:"不善果報心",en:"unwholesome resultant",pli:"akusalavipāka"},
{id:"vipakacitta",zh:"果報心",or:"#kusalavipaka#akusalavipaka",en:"resultant consciousness",pli:"vipaka citta",pli:"vipākacitta"},
{id:"kiriyacitta",stem:"#kiriya",zh:"唯作心",en:"functional consciousness",pli:"kiriya citta"},
{id:"arahantsmile",zh:"阿羅漢之生笑",def:"有五個能令#arahant;微笑之心",has:"#hasituppadacitta#kamavacarasomanassasahagatakiriyacitta",en:"smile of arahant",pli:"-"},
{id:"kamavacarasomanassasahagatakiriyacitta",attr:"#somanassasahagata",zh:"欲界悅俱唯作心",stem:"#8kamavacarakiriyacitta",def:"共四個",en:"sense-sphere functional consciousness accompanied by joy",pli:"kamavacarasomanassasahagatakiriyacitta"},
{id:"sobhanacitta",zh:"美心",attr:"#kusala#abyakata" ,def:"除惡及無因，餘者皆為美。pāpāhetukamuttāni sobhanānī ti",en:"beautiful consciousness",pli:"sobhanacitta",has:"#24kamavacarasobhanacitta#rupavacaracitta#arupavacaracitta#lokuttaracitta"},
{id:"abyakata",zh:"無記",pli:"abyākata",has:"#kiriya#vipaka",en:"kammically indeterminate"},
{id:"24kamavacarasobhanacitta",zh:"24欲界美心",stem:"#kamavacara",en:"24 sense-sphere beautiful consciousness",pli:"kāmāvacara sobhana",has:"#8kamavacarakusalacitta#8kamavacaravipakacitta#8kamavacarakiriyacitta"},
{id:"8kamavacarakusalacitta",zh:"8欲界善心|大善心",attr:"#sahetuka",func:"#javana",stem:"#kamavacara#kusalacitta",or1:"#somanassasahagata#upekkhasahagata",or2:"#nanasampayuta#nanavippayuta",or3:"#sasankharika#asankharika",en:"8 sense-sphere wholesome consciousness",pli:"kāmāvacara kusala|mahākusaka citta"},
{id:"nanasampayuta",zh:"智相應",en:"associated with wisdom",pli:"ñāṇasampayuta"},
{id:"nanavippayuta",zh:"智不相應",en:"associated with wisdom",pli:"ñāṇavippayuta"},
{id:"8kamavacaravipakacitta",zh:"8欲界果報心|大果報心",func:"#patisandhi#tadarammana",attr:"#sahetuka",stem:"#kamavacara#vipakacitta",or1:"#somanassasahagata#upekkhasahagata",or2:"#nanasampayuta#nanavippayuta",or3:"#sasankharika#asankharika",en:"8 sense-sphere resultant consciousness",pli:"kāmāvacara vipakā|mahāvivipakā citta",def:"為了區別它們和善果報無因心，所以稱之為「有因」（sahetuka）。無因與有因的善果報心都是由同樣的八種善心所產生，但這兩組心在各自的素質與作用方面則有差別。概要精解pg32"},
{id:"8kamavacarakiriyacitta",zh:"8欲界唯作心|大唯作心",func:"#javana",stem:"#kamavacara#kiriyacitta",attr:"#sahetuka",or1:"#somanassasahagata#upekkhasahagata",or2:"#nanasampayuta#nanavippayuta",or3:"#sasankharika#asankharika",en:"8 sense-sphere functional consciousness",pli:"kāmāvacara kiriya|mahākiriya citta"},


{id:"cetasika",zh:"心所",en:"mental factor",pli:"cetasika",types:"#7sabbacittasadharana#6pakinnaka#14akusala#25sobhana",def:"一、與心同生（ekuppāda）；二、 與心同滅（ekanirodha）；三、 與心緣取同一目標（ekālambana）；四、 與心擁有同一依處（ekavatthuka）。概要精解pg58"},
{id:"7sabbacittasadharana",is:"#cetasika",zh:"7遍一切心心所",en:"seven universal",pli:"sabba citta sādhāraṇa",has:"#phassa#vedana#sanna#cetana#ekaggata#jivit#manasikara"},
{id:"6pakinnaka",zh:"6雜心所",en:"six occasional",pli:"pakinnaka cetasika",has:"#vitakka#vicara#adhimokkha#viriya#piti#chanda"},
{id:"14akusala",zh:"14不善心所",en:"fourteen unwholesome",pli:"akusalacetasika",has:"#moha#ahirika#anottappa#uddhacca#lobha#ditthi#mana#dosa#issa#macchariya#kukkucca#thina#middha#vicikiccha"},

{id:"jivit",zh:"名法命根",pli:"jivita",en:"life faculty"},
{id:"vitakka",zh:"尋",en:"initial application",pli:"vitakka"},
{id:"vicara",zh:"伺",en:"sustained application",pli:"vicara"},
{id:"adhimokkha",zh:"勝解",en:"decision",pli:"adhimokkha"},
{id:"ekaggata",zh:"一境性",en:"one pointedness",pli:"ekaggatā"},
{id:"manasikara",zh:"作意",en:"attension",pli:"attention"},
{id:"piti",zh:"喜",en:"zest",pli:"pīti"},
{id:"cetana",zh:"思",def:"負責造#kamma;",en:"volition",pli:"cetanā"},
{id:"chanda",zh:"欲",en:"desire",pli:"chanda"},
{id:"moha",zh:"痴",en:"delusion",pli:"moha"},
{id:"ahirika",zh:"無慚",en:"shamelessness",pli:"ahirīka"},
{id:"anottappa",zh:"無悔",en:"fearlessness of wrong",pli:"anottāppa"},
{id:"uddhacca",zh:"掉舉",en:"restlessness",pli:"uddhacca"},
{id:"lobha",zh:"貪",en:"greed",pli:"lobha"},
{id:"ditthi",zh:"邪見",en:"wrong view",pli:"diṭṭhi"},
{id:"mana",zh:"慢",en:"conceit",pli:"māna"},
{id:"dosa",zh:"瞋",en:"hatred",pli:"dosa"},
{id:"issa",zh:"嫉",en:"envy",pli:"issa"},
{id:"macchariya",zh:"慳",en:"avarice",pli:"macchariya"},
{id:"kukkucca",zh:"悔",en:"worry",pli:"kukkucca"},
{id:"thina",zh:"昏沉",en:"sloth",pli:"thīna"},
{id:"middha",zh:"睡眠",en:"torpor",pli:"middha",with:"#sasankharika"},
{id:"vicikiccha",zh:"疑",en:"doubt",pli:"vicikicchā",with:"#sasankharika",
def:"vicikicchā，諸論師提出兩個詞源學的說明：一、由於思緒紛雜困亂而致的困惑（vici (vicinanto) = 詢問 + kicch = 受到困擾；）；二、缺少智慧解決問題。（vi = 毫無 + cikiccha = 解決方案。）概要精解pg19腳注"},

{id:"saddhapanna",zh:"信慧組",def:"加上識即初禪34名法",has:"#7sabbacittasadharana#6pakinnaka#19sobhanasadharana#pannindriya",en:"group with faith and wisdom",pli:"saddhapañña"},
{id:"25sobhana",zh:"25美心所",en:"25 beautiful factors",pli:"sobhaṇacetasika",has:"#19sobhanasadharana#3virati#2appamanna#1amoha"},
{id:"19sobhanasadharana",zh:"19遍一切美心心所",en:"universal beautiful factors",pli:"sobhaṇasādhāraṇa",has:"#saddha#sati#hiri#ottappa#alobha#adosa#tatramajjhattata#kayapassaddhi#cittapassaddhi#kayalahuta#cittalahuta#kayamuduta#cittamuduta#kayakammabbata#cittakammabbata#kayapagubbata#cittapagubbata#kayujjukata#cittujjukata"},
{id:"saddha",zh:"信",en:"faith",pli:"saddha"},
{id:"sati",zh:"念",en:"mindfullness",pli:"sati"},
{id:"hiri",zh:"慚",en:"shame",pli:"hirī"},
{id:"ottappa",zh:"愧",en:"fear of wrong",pli:"ottappa"},
{id:"alobha",zh:"無貪",en:"non-greed",pli:"alobha"},
{id:"adosa",zh:"無瞋",en:"non-hatred",pli:"adosa"},
{id:"tatramajjhattata",zh:"中捨",en:"neutrality of mind",pli:"tatramajjhattatā"},
{id:"passaddhi",zh:"輕安",en:"tranquality",pli:"passaddhi"},
{id:"kayapassaddhi",zh:"身輕安",en:"tranquality of mental body",pli:"kāyapassaddhi",stem:"passaddhi"},
{id:"cittapassaddhi",zh:"心輕安",en:"tranquality of consciousness",pli:"cittapassaddhi",stem:"passaddhi"},
{id:"kayalahuta",zh:"身輕快",en:"lightness of mental body",pli:"kāyalahutā"},
{id:"cittalahuta",zh:"心輕快",en:"lightness of consciousness",pli:"cittalahutā"},
{id:"kayamuduta",zh:"身柔軟",en:"malleability of mental body",pli:"kāyamudutā"},
{id:"cittamuduta",zh:"心柔軟",en:"malleability of consciousness",pli:"cittamudutā"},
{id:"kayakammabbata",zh:"身適業",en:"wieldiness of mental body",pli:"kāyakammaññatā"},
{id:"cittakammabbata",zh:"心適業",en:"wieldiness of consciousness",pli:"cittakammaññatā"},
{id:"kayapagubbata",zh:"身練達",en:"proficiency of mental body",pli:"kāyapaguññatā"},
{id:"cittapagubbata",zh:"心練達",en:"proficiency of consciousness",pli:"cittapaguññatā"},
{id:"kayujjukata",zh:"身正直",en:"rectitude of mental body",pli:"kāyujjukatā"},
{id:"cittujjukata",zh:"心正直",en:"rectitude of consciousness",pli:"cittujjukatā"},
{id:"3virati",zh:"3離心所",en:"three abstinence",pli:"virati",has:"#sammavaca#sammakammanta#sammaajiva"},
{id:"sammavaca",zh:"正語",def:"虛妄語（musāvāda）、離間語（pisuṇā vācā）、粗惡語（pharusā vācā）、雜穢語（samphappalāpa）。",en:"right speech",pli:"sammāvācā"},

{id:"2appamanna",zh:"2無量心所",en:"two illimitables",pli:"appamāṇa",has:"#karuna#mudita"},
{id:"karuna",zh:"悲",en:"compassion",pli:"karuṇā"},
{id:"mudita",zh:"隨喜",en:"appreciative joy",pli:"muditā"},

{id:"1amoha",zh:"1無痴",en:"non delusion",pli:"amoha",has:"#pannindriya"},
{id:"pannindriya",zh:"慧根",en:"wisdom faculty",pli:"paññindriya",stem:"#panna#indriya"},
{id:"vithi",zh:"心路過程",en:"mental process",pli:"vithi"},
{id:"patisandhi",zh:"結生",en:"rebirth linking",pli:"paṭisandhi"},
{id:"patisandhicitta",zh:"結生心",en:"rebirth linking consciousness",pli:"paṭisandhicitta",stem:"patisandhi"},
{id:"dvaravimutta",zh:"離門心",syn:"#vithimuttacitta",en:"door-freed",pli:"dvāravimutta",has:"#8kamavacarakusalacitta#5rupavacaravipakacitta#4arupavacaravipakacitta#upekkhasahagatasantiranacitta"},
{id:"vithimutta",zh:"離心路過程",en:"process-free",pli:"vithimutta",stem:"#vithi"},
{id:"vithimuttacitta",zh:"離心路心",en:"process-freed consciousness",pli:"vīthimutta",arm:"#kamma#kammanimitta#gatinimitta",has:"#patisandhicitta#bhavanga#cuticitta",stem:"#vithimutta"},
{id:"cuticitta",zh:"死亡心",en:"death consciousness",pli:"cuticitta"},

{id:"javana",zh:"速行",en:"impulsion",pli:"javana"},
{id:"javanacitta",zh:"速行心",en:"impulsion mind moment",pli:"javanacittakhana"},
{id:"kamavacarajavana",zh:"29欲界速行",en:"sense-sphere impulsion",pli:"kāmāvacarajavana",has:"#12akusakacitta#8kamavacarakusalacitta#8kamavacarakiriyacitta#hasituppadacitta"},
{id:"tadarammana",zh:"彼所緣",en:"registration",pli:"tadārammaṇa"},

{id:"pancadvaravithi",zh:"五門心路",is:"#vithi",stem:"#pancadvara",en:"five door cognitive process",pli:"pañcadvāravīthi"},
{id:"pancadvara",zh:"五門",is:"#rupadhamma",en:"mind door",pli:"pañcadvāra"},
{id:"manodvara",zh:"意門",syn:"#bhavanga",is:"#nama",en:"mind door",pli:"manodvāra"},
{id:"manodvaravithi",zh:"意門心路",is:"#vithi",en:"mind door cognitive process",pli:"manodvāravīthi"},
{id:"appanavithi",zh:"安止心路",is:"#vithi",en:"process of absorption",pli:"appanāvīthi",has:"#rupavacaracitta#arupavacaracitta"},

{id:"cattaricatukkha",zh:"四個四",types:"#vithimutta",en:"set of fours",pli:"catāricatukkha",has:"#bhumicattukka#patisandhicatukka#kammacatukka"},
{id:"bhumicattukka",zh:"四生存地",en:"the four planes of existence",pli:"bhūmicatukka",has:"#apayabhumi#kamasugatibhumi#rupavacarabhumi#arupavacarabhumi"},

{id:"apayabhumi",zh:"惡趣地",has:"#niraya#tiracchanayoni#pettivisaya#asurakaya",en:"the woeful plane",pli:"apāyabhūmi",has:"#apayapatisandhi"},
{id:"niraya",zh:"地獄|泥犁",en:"hell",pli:"niraya"},
//中部講地獄的經
{id:"kamasugatibhumi",zh:"欲善趣地",has:"#manussa#catummaharajika#tavatimsa#tusita#nimmanarati#paranimmitavasavatti",en:"the sensuous blissful plane",pli:"kāmasugatibhūmi",has:"#kamasugatipatisandhi"},
{id:"manussa",zh:"人間",def:"",en:"human realm",pli:"manussa"},

{id:"rupavacarabhumi",zh:"色界地",stem:"#rupavacara",has:"#pathamajjhanabhumi#dutiyajjhanabhumi#tatiyajjhanabhumi#catutthajjhanabhumi",en:"fine-material realm",pli:"rūpāvacarabhūmi",has:"#rupavacarapatisandhi"},

{id:"arupavacarabhumi",zh:"無色界地",en:"immaterial realm",pli:"arūpāvacarabhūmi",has:"#akasanancayatanabhumi#vinnanancayatanabhumi#akincannayatanabhumi#nevasannanasannayatanabhumi",stem:"#arupavacara",has:"#arupavacarapatisandhi"},

{id:"patisandhicatukka",zh:"四種結生",has:"#apayapatisandhi#kamasugatipatisandhi#rupavacarapatisandhi#arupavacarapatisandhi",en:"four types of rebirth linking",pli:"paṭisandhicatukka",stem:"patisandhi"},
{id:"apayapatisandhi",zh:"惡趣結生",def:"唯一方式#akusalavipaka;的#upekkhasahagatasantiranacitta;",en:"rebirth linking in woeful plane",pli:"apāyapaṭisandhi",stem:"#apayabhumi"},
{id:"kamasugatipatisandhi",zh:"欲善趣結生",def:"以#kusalavipaka;的#upekkhasahagatasantiranacitta;成為先天殘缺的人類、某些地神、某些#asurakaya;的#patisandhicitta;。 #8kamavacaravipakacitta;能作為一切#kamasugatibhumi;的#patisandhicitta; #bhavanga; #cuticitta;",en:"rebirth linking in sensuous blissful plane",pli:"kāmasugatipaṭisandhi"},
{id:"rupavacarapatisandhi",zh:"色界結生",def:" #5rupavacaravipakacitta; 為其相應之#patisandhicitta; 對無想有情，色法本身生起為結生",en:"rebirth linking in fine-material sphere",pli:"rūpavacarapaṭisandhi"},
{id:"arupavacarapatisandhi",zh:"無色界結生",def:" #4arupavacaravipakacitta; 為其相應之#patisandhicitta; ",en:"rebirth linking in immaterial sphere",pli:"arūpavacarapaṭisandhi"},

{id:"kammacatukka",zh:"四種業",en:"four types of kamma",pli:"kammacatukkha",types:"#kiccavasena#pakadanapariyayena#pakakalavasena"},
{id:"kiccavasena",zh:"依作用",en:"by way of function",pli:"kiccavasena",has:"#janaka#upatthambaka#upapilaka#upaghataka"},
{id:"janaka",zh:"令生業",en:"productive kamma",pli:"janaka"},
{id:"upatthambaka",zh:"支助業",en:"supportive kamma",pli:"upatthambaka"},
{id:"upapilaka",zh:"阻礙業",en:"obstructive kamma",pli:"upapīḷaka"},
{id:"upaghataka",zh:"毀壞業",en:"destructive",pli:"upaghātaka"},

{id:"pakadanapariyayena",zh:"依成熟之順序",has:"#garukakamma#anantariya#asannakamma#acinnakamma",en:"by order of ripening",pli:"pākadana pariyayena"},
{id:"garukakamma",zh:"重業",syn:"#anantariya",en:"weighty kamma",pli:"garukakamma"},
{id:"anantariya",zh:"無間業",en:"five heinous crimes",pli:"ānantariya"},
{id:"asannakamma",zh:"臨死業",en:"death-proximate kamma",pli:"āsannakamma"},
{id:"acinnakamma",zh:"慣行業",en:"habitual kamma",pli:"āciṇṇakamma"},
{id:"katatta",zh:"已作業",en:"reserve",pli:"kaṭatta"},
{id:"pakakalavasena",zh:"依成熟之時間",has:"#ditthadhammavedaniya#upapajjavedaniya#apapariyavedaniya#ahosikamma",en:"by time of ripening",pli:"pākakālavasena"},

{id:"ditthadhammavedaniya",zh:"現生受業",def:"由第一個#javanacitta;所造之#kamma; 無機會成熟即為#ahosikamma;",en:"immediately effective kamma",pli:"diṭṭhadhammavedanīya kamma"},
{id:"upapajjavedaniya",zh:"次生受業",def:"由第七個#javanacitta;所造之#kamma;。無機會成熟即為#ahosikamma;",en:"subsequently effective kamma",pli:"upapajjavedanīya kamma"},
{id:"apapariyavedaniya",zh:"無盡業",def:"由第二到第六個#javanacitta;所造之#kamma;。只要還在輪迴，它即永遠不會變成無效。沒有任何人能夠免除體驗無盡業的果報，即使佛陀與阿羅漢也不例外。 ",en:"indefinitely effective kamma",pli:"apāpariyavedanīya"},
{id:"ahosikamma",zh:"無效業",en:"defunct kamma",pli:"ahosikamma"},



{id:"pakatthanavasena",zh:"依成熟之地",def:"不善業,欲界善業,色界善業,無色界善業",en:"by place of ripening",pli:"pākaṭṭhānavasena"},


{id:"bhavanga",zh:"有分",en:"life-continuum",pli:"bhavaṅga"},
{id:"kammanimitta",zh:"業相",en:"sign of kamma",pli:"kammanimitta"},
{id:"gatinimitta",zh:"趣相",en:"sign of destiny",pli:"gatinimitta"},

{id:"10samyojana",zh:"10結",has:"#kamaraga#ruparaga#aruparaga#patigha#mana#ditthi#silabbataparamasa#vicikiccha#uddhacca#avijja",en:"10 fetters",pli:"Saṁyojana"},
{id:"kamaraga",zh:"欲貪",en:"attachment to sensual lust",pli:"kāmarāga"},
{id:"ruparaga",zh:"色貪",en:"attachment to fine-material existence",pli:"rūparāga"},
{id:"aruparaga",zh:"無色貪",en:"attachment to immaterial existence",pli:"arūparāga"},
{id:"3samyojana",zh:"3結",has:"#sakayaditti#vicikiccha#silabbataparamasa", en:"3 fetters",pli:"tīṇi saṁyojana"},
{id:"sakayaditti",zh:"(有)身見",en:"personality view",pli:"sakkāya-diṭṭi",stem:"ditthi"}, 
{id:"silabbataparamasa",zh:"戒禁取",en:"adherence to rites and ceremonies",pli:"sīlabbata-parāmasa"},

{id:"dana",zh:"布施",en:"offering",pli:"dāna"},
{id:"sila",zh:"持戒",en:"morality",pli:"sīla"},
{id:"sacca",zh:"諦",en:"truth",pli:"sacca"},
{id:"panna",zh:"慧",en:"wisdom",pli:"pañña"},
{id:"nana",zh:"智",en:"insight knowledge",pli:"ñāṇa"},
{id:"khanti",zh:"忍耐",en:"patience",pli:"khanti"},
{id:"viriya",zh:"精進",en:"energy",pli:"viriya"},
{id:"metta",zh:"慈",en:"loving kindness",pli:"metta"},
{id:"adhitthana",zh:"決意",en:"determination",pli:"adhiṭṭhahāna"},
{id:"upekkha",zh:"捨",is:"#vedana",en:"equanimity",pli:"upekkha",
def:"譯按：巴利文 upekkha 一詞有多種不同的意義。在此列出較常見的幾個：一、此節所提及的「捨俱」是「與捨受俱行」，此捨受是「受心所」（vedanā-cetasika）；二、五禪支裡的捨也是屬於受心所；三、捨覺支與捨梵住或捨無量心的捨是「中捨性心所」（tatramajjhattatā）；四、觀禪的行捨智則屬於「慧心所」（paññā-cetasika）。五、「精進捨」是不過強亦不太弱而適中的精進，是屬於精進心所（virīya-cetasika）。概要精解pg15"
},
{id:"nekkhamma",zh:"出離",en:"renounciation",pli:"nekkhamma"},


{id:"10parami",	zh:"十波羅密",en:"10 perfections",pli:"dasa paramiyo",has:"#dana#sila#khanti#viriya#adhitthana#nekkhamma#sacca#metta#upekkha#panna",
},
{id:"nama",zh:"名",en:"mentality",pli:"nāma",types:"#citta#cetasika"},
{id:"rupa",zh:"色",en:"material phenomena|materiality",pli:"rūpa"},
{id:"rupadhamma",is:"dhamma",stem:"#rupa",en:"mentality dhamma",pli:"rūpa dhamma",zh:"色法"},
{id:"4mahabhuta",
	is:"#nipphannarupa",
	has:"#pathavi#apo#tejo#vayo",
	zh:"四大",
	en:"four elements",
	pli:"cātummahābhūtika"
},
{id:"nipphannarupa",is:"#rupa",attr:"#sabhavarupa#salakkhanarupa#ruparupa#sammasanarupa",zh:"完成色",pli:"nipphannarūpa",en:"concretely produced matter|real rupa"},
{id:"sabhavarupa",zh:"有自性色",en:"matter possessing intrinsic nature",pli:"sabhātvarūpa"},
{id:"salakkhanarupa",zh:"有相色",en:"matter possessing real characteristic",pli:"salakkhaṇarūpa",def:"有#anicca;、#dukkha;、#anatta;三相"},
{id:"ruparupa",zh:"色色",en:"material matter",pli:"rūparūpa"},
{id:"sammasanarupa",zh:"思惟色",def:"可作為#vipassana;的目標",en:"matter to be comprehended by insight",pli:"sammasanarūpa"},



{id:"pathavi",	pli:"paṭhavī",	en:"earth element",	zh:"地大"},
{id:"apo",	pli:"apo",	en:"water element",	zh:"水大"},	
{id:"tejo",	pli:"tejo",	en:"water element",	zh:"火大"},
{id:"vayo",	pli:"vāyo",	en:"water element",	zh:"風大"},	

{id:"pathavidhatu",zh:"地界",stem:"#pathavi",pli:"paṭhavīdhātu",	en:"earth element"},
{id:"apodhatu",	zh:"水界",stem:"#apo",pli:"apodhātu",en:"water element"},
{id:"tejodhatu",zh:"火界",stem:"#tejo",pli:"tejodhātu",en:"water element"},
{id:"vayodhatu",zh:"風界",stem:"#vayo",pli:"vāyodhātu",en:"water element"},	
{id:"bhutarupa",zh:"元素色",is:"#nipphannarupa",en:"essential material phenomena",pli:"bhūtarūpa",has:"#pathavidhatu#apodhatu#tejodhatu#bhutarupa"},
{id:"upadayarupa",zh:"所造色",is:"#rupa",en:"derived material phenomena",pli:"upādāyarūpa"},
{id:"gocararupa",zh:"境色",is:"#nipphannarupa",en:"objective material phenomena",pli:"#gocararūpa", has:"#ruparammana#sadda#gandha#rasarammana#photthabba",en:"",pli:"gocararupa"},

{id:"itthabhavarupa",zh:"女根色",en:"femininity",pli:"itthabhāvarūpa"},
{id:"purisabhavarupa",zh:"男根色",en:"masculinity",pli:"purisabhāvarūpa"},
{id:"bhavarupa",is:"#nipphannarupa",
	types:"#purisabhavarupa#itthabhavarupa",
	zh:"性根色",en:"sex mentality phenomena",pli:"bhāvarūpa"
},
{id:"hadayarupa",zh:"心色",has:"#hadayavatthu",en:"heart mentality phenomena",pli:"hadaya rūpa"},
{id:"hadayavatthu",zh:"心所依處色",en:"heart base mentality phenomena",pli:"hadayavatthu"},
{id:"jivitarupa",zh:"命色",has:"#jivitindriya",en:"live mentality phenomena",pli:"jīvitarūpa"},
{id:"jivitindriya",zh:"命根色",is:"#nipphannarupa",en:"live faculty",pli:"jivitindriya"},
{id:"ahararupa",zh:"食色",has:"#ahara",en:"nutriment material phenomena",pli:"ahararūpa"},
{id:"kabalikahara",zh:"段食",is:"#nipphannarupa",en:"editable food",pli:"kabaḷikāhararūpa"},
{id:"ahara",zh:"食",types:"#cattaroahara",en:"nutriment",pli:"ahara"},
{id:"cattaroahara",zh:"四食",en:"nutriment",has:"#kabalikahara#phassa#manosancetana#vinnana",pli:"cattāro āhāra"},
{id:"manosancetana",zh:"意思(食)",en:"",pli:"manosañcetanā"},
{id:"anipphannarupa",is:"#upadayarupa",zh:"不完成色",en:"non-concrete matter|non real rupa",pli:"anipphannarūpa"},

{id:"paricchedarupa",zh:"限制色",is:"#anipphannarupa",en:"limiting material phenomena",pli:"paricchedarūpa",has:"#akasadhatu"},
{id:"akasadhatu",zh:"空界",en:"space element",pli:"ākāsadhātu"},
{id:"vinnatirupa",zh:"表色",is:"#anipphannarupa",en:"intimating material phenomena",pli:"viññātirūpa",has:"#kayavinnatti#vacivinnatti"},
{id:"kayavinnatti",zh:"身表",en:"bodily intimation",pli:"kāyaviññatti"},
{id:"vacivinnatti",zh:"語表",en:"vocal intimation",pli:"vacīviññatti"},

{id:"5vikararupa",zh:"變化色",is:"#anipphannarupa",en:"intimating material phenomena",pli:"vikārarūpa",has:"#rupassalahuta#rupassamuduta#rupassakammannata#vinnatirupa"},

{id:"rupassalahuta",zh:"色輕快性",en:"material lightness",pli:"rūpassa-lahutā"},
{id:"rupassamuduta",zh:"色柔軟性",en:"material malleability",pli:"rūpassa-mudutā"},
{id:"rupassakammannata",zh:"色適業性",en:"material wieldiness",pli:"rūpassa-kammaññatā"},

{id:"lakkhanarupa",zh:"相色",has:"#rupassaupacaya#rupassasantati#rupassajarata#rupassaaniccata",en:"characteristic of material phenomena",pli:"lakkhaṇarūpa"},
{id:"rupassaupacaya",zh:"色積集",en:"production of material phenomena",pli:"rūpassa-upacaya",def:"指在#patisandhi;時刻生起的#kaya10; #bhava10; #hadaya10;"},
{id:"rupassasantati",zh:"色相續",en:"continuity of material phenomena",pli:"rūpassa-santati"},
{id:"rupassajarata",zh:"色老性",en:"decay of material phenomena",pli:"rūpassa-jaratā"},
{id:"rupassaaniccata",zh:"色無常性",en:"impermanence of material phenomena",pli:"rūpassa-aniccatā"},


{id:"tiloka",zh:"三界",en:"three worlds",pli:"tiloka",types:"#kamaloka#rupaloka#arupaloka"},
{id:"kamaloka",zh:"欲世界",en:"sensuous world",pli:"kāmaloka"},
{id:"rupaloka",zh:"色世界",en:"fine-material world",pli:"rūpaloka"},

{id:"arupa",zh:"無色",en:"immaterial",pli:"arūpa"},
{id:"arupaloka",zh:"無色世界",en:"immaterial world",pli:"arūpaloka"},

{id:"namarupa",zh:"名色",en:"mentality and materiality",pli:"nāmarūpa",stem:"#nama#rupa"},
{id:"avijja",zh:"無明",anto:"#vijja",en:"ignorant",pli:"avijja"},
{id:"vijja",zh:"明",en:"knowledge",pli:"vijja"},
{id:"ayatana",zh:"入處|感官",en:"sense door",pli:"āyatana"},
{id:"salayatana",stem:"#ayatana",zh:"六入",en:"six sense doors",pli:"saḷāyatana"},
{id:"phassa",zh:"觸",amb:"#photthabba",en:"contact",pli:"phassa"},
{id:"tanha",zh:"貪愛",en:"craving",pli:"taṇhā"},
{id:"upadana",zh:"取",en:"attachment",pli:"upādāna"},
{id:"bhava",zh:"有",en:"becoming",pli:"bhāva"},
{id:"jati",zh:"生",en:"birth",pli:"jaṭī"},
{id:"jara",zh:"老",en:"aging",pli:"jara"},
{id:"marana",zh:"死",en:"death",pli:"maraṇa"},
{id:"somanassa",zh:"悅",en:"joy",pli:"somanassa"},
{id:"domanassa",zh:"憂",en:"grief|displeasure",pli:"domanassa"},
{id:"jara_etc",zh:"老死等",en:"aging and so on", has:"#jara#marana#soka#parideva#dukkha#domanassa#upayasa",pli:"jara pe.."},
{id:"soka",zh:"愁",en:"sorrow",pli:"soka"},
{id:"parideva",zh:"悲",en:"lamentation",pli:"parideva"},
{id:"upayasa",zh:"惱",en:"despair",pli:"upāyāsa"},
{id:"paticcasamuppada",zh:"緣起",en:"dependent origination",pli:"paṭicca-samuppāda",types:"#12samuppada#3vatta"},
{id:"12samuppada",zh:"十二支緣起",
has:"#avijja#sankhara#vinnana#namarupa#salayatana#phassa#vedana#tanha#upadana#bhava#jati#jara_etc",en:"dependent origination",pli:"paṭicca-samuppāda"},

{id:"avacara",zh:"界",en:"realm",pli:"avacara"},
{id:"kama",zh:"欲|愛慾",amb:"#chanda",en:"lust",pli:"kāma"},
{id:"kamavacara",zh:"欲界",stem:"#kama#avacara",en:"sense-sphere realm",pli:"kāmâvacara"},
{id:"rupavacara",zh:"色界",stem:"#rupa#avacara",en:"fine-material realm",pli:"rupâvacara"},
{id:"arupavacara",zh:"無色界",stem:"#arupa#avacara",en:"immaterial realm",pli:"arūpâvacara"},
   
{id:"bhumi",zh:"地",amb:"#pathavi",pli:"bhūmi",en:"ground|earth|region|plane"},


{id:"cakkhu",zh:"眼",en:"eye",pli:"cakkhu"},
{id:"sota",zh:"耳",en:"ear",pli:"sota"},
{id:"ghana",zh:"鼻",en:"nose",pli:"ghāna"},
{id:"jivha",zh:"舌",en:"tongue",pli:"jivhā"},
{id:"kaya",zh:"身",en:"body",pli:"kāya"},

{id:"photthabba",zh:"踫觸",has:"#pathavidhatu#tejodhatu#vayodhatu",en:"touch",pli:"phoṭṭhabba"},
{id:"ruparammana",zh:"色塵",en:"visible object",pli:"rūpārammaṇa"},
{id:"sadda",zh:"聲",en:"sound",pli:"sadda"},
{id:"gandha",	zh:"香",	en:"odour",id:"gandha",pli:"gandha"},
{id:"rasarammana",	zh:"味",	en:"taste",pli:"rasārammaṇa"},
{id:"dhammarammana",zh:"法塵",en:"mental object",pli:"dhammārammaṇa"},
{id:"vanna",	zh:"顏色",	en:"color",pli:"vaṇṇa"},
{id:"oja",	zh:"食素",	en:"nutritive essense",pli:"oja"},
{id:"avinibbhogarupa",
	has:"#4mahabhuta#gandha#rasa#vanna#oja",
	en:"8 inseparable rupa",
	zh:"八不離色",
	pli:"avinibbhogarūpa"
},
{id:"jivita",	en:"life faculty",	zh:"命根色",pli:"jīvita"},


{id:"kammasamutthana",	zh:"業生",en:"kamma born",pli:"kammasamuṭṭhāna",has:"#8kalapa#indriya10#jivita9#bhava10#hadaya10#akasadhatu"},
{id:"cittasamutthana",	zh:"心生",def:"心在最強的生時產生色法",has:"#8kalapa#5vikararupa#sadda#akasadhatu",en:"mind born",pli:"cittasamuṭṭhāna"},
{id:"utusamutthana",	zh:"時節生",has:"#8kalapa#rupassalahuta#rupassamuduta#rupassakammannata#sadda#akasadhatu",en:"temperature born",pli:"utusamuṭṭhāna"},
{id:"aharasamutthana",	zh:"食生",def:"10~12代，一天食物可維持七天",has:"#8kalapa#rupassalahuta#rupassamuduta#rupassakammannata#akasadhatu",en:"nutriment born",pli:"āhārasamuṭṭhāna"},
{id:"4rupasamutthana",zh:"4色法生起之源",has:"#kammasamutthana#cittasamutthana#utusamutthana#aharasamutthana",en:"four mode of origination of matter",pli:"rūpasamuṭṭhāna"},
{id:"kalapa",
	is:"#rupadhamma",
	has:"#avinibbhogarupa",
	types:"#8kalapa#9kalapa#10kalapa#11kalapa#12kalapa#13kalapa",
	zh:"色聚",en:"particle",pli:"kalāpa"
},
{id:"kammajakalapa",
	is:"#kalapa",
	has:"#jivita",
	attr:"#kammasamutthana",
	zh:"業生色聚",
	en:"kamma born kalāpa",
	pli:"kammajakalapa"
},
{id:"cittajakalapa",
	is:"#kalapa",
	attr:"#cittasamutthana",
	zh:"心生色聚",
	en:"mind born kalāpa",
	pli:"cittaja kalāpa"
},
{id:"utujakalapa",
	is:"#kalapa",
	attr:"#utusamutthana",
	zh:"時節生色聚",
	en:"temperature born kalāpa",
	pli:"utuja kalāpa"
},
{id:"aharajakalapa",
	is:"#kalapa",
	attr:"#aharasamutthana",
	zh:"食生色聚",
	en:"nutriment born kalāpa",
	pli:"āhāraja kalāpa"
},
{id:"cakkhupasada",stem:"#cakkhu",en:"eye translucency",zh:"眼浄色",pli:"cakkhupasada"},
{id:"sotapasada",stem:"#sota",en:"ear translucency",zh:"耳浄色",pli:"sotapasada"},
{id:"ghanapasada",stem:"#ghana",en:"nose translucency",zh:"鼻浄色",pli:"ghānapasada"},
{id:"jivhapasada",stem:"#jivha",en:"tongue translucency",zh:"舌浄色",pli:"jivhāpasada"},
{id:"kayapasada",stem:"#kaya",en:"body translucency",zh:"身浄色",pli:"kāyapasada"},
{id:"pasada",
	attr:"#kammasamutthana",zh:"明淨色",	en:"translucency",pli:"pasada",
	types:"#cakkhupasada#sotapasada#ghanapasada#jivhapasada#kayapasada"
},
{id:"8kalapa",has:"#avinibbhogarupa",zh:"八法聚",	en:"octad kalapa",pli:"aṭṭhaka kalāpa"},
{id:"9kalapa",has:"#avinibbhogarupa",zh:"九法聚",	en:"nonad kalapa",pli:"navaka kalāpa"},
{id:"10kalapa",has:"#avinibbhogarupa",zh:"十法聚",	en:"decad kalapa",pli:"dasaka kalāpa",},
{id:"11kalapa",has:"#avinibbhogarupa",zh:"十一法聚",	en:"un-decad kalapa",pli:"ekādasaka kalāpa",},
{id:"12kalapa",has:"#avinibbhogarupa",zh:"十二法聚",	en:"dodecad kalapa",pli:" dvidasaka kalāpa",},
{id:"13kalapa",has:"#avinibbhogarupa",zh:"十三法聚",	en:"tridecad kalapa",pli:" teḷasa kalāpa",},
{id:"indriya10",zh:"五根十法聚",en:"faculty decad kalapa",pli:"indriya dasaka"},
{id:"cakkhu10",
	is:"#kammajakalapa#10kalapa",
	has:"#cakkhupasada",
	pli:"cakkhu dasaka kalāpa",
	zh:"眼十法聚",
	en:"eye decad kalapa"
},
{id:"sota10",
	is:"#kammajakalapa#10kalapa",
	has:"#sotapasada",
	pli:"sota dasaka kalāpa",
	zh:"耳十法聚",
	en:"ear decad kalapa"
},
{id:"ghana10",
	is:"#kammajakalapa#10kalapa",
	has:"#ghanapasada",
	pli:"ghāna dasaka kalāpa",
	zh:"鼻十法聚",
	en:"nose decad kalapa"
},
{id:"jivha10",
	is:"#kammajakalapa#10kalapa",
	has:"#jivhapasada",
	pli:"jivhā dasaka kalāpa",
	zh:"舌十法聚",
	en:"tongue decad kalapa"
},  
{id:"kaya10",
	is:"#kammajakalapa#10kalapa",
	has:"#kayapasada",
	pli:"kāya dasaka kalāpa",
	zh:"身十法聚",
	en:"body decad kalapa"
},

{id:"bhava10",
	is:"#kammajakalapa#10kalapa",
	has:"#bhavarupa",
	pli:"bhāva dasaka kalāpa",
	zh:"性根十法聚",
	en:"bhava decad kalapa"
},
{id:"hadaya10",
	is:"#kammajakalapa#10kalapa",
	has:"#hadayarupa",
	zh:"心十法聚",
	en:"heart decad kalapa",
pli:"hadaya dasaka kalāpa",
},
{id:"jivita9",	zh:"命根九法聚",is:"#kammajakalapa#9kalapa",has:"#jivita",en:"life nonad kalapa",pli:"jīvitanavaka"},


{id:"cittaja8",	zh:"心生純八法聚",is:"#cittajakalapa#8kalapa",en:"mind born pure octad kalapa",pli:"cittaja suddhaṭṭhaka"},
{id:"kayavinnatti9",	zh:"身表九法聚",is:"#cittajakalapa#9kalapa",has:"#kayavinnatti",en:"bodily intimation nonad kalapa",pli:"kāyaviññatti navaka"},
{id:"vacivinnatti9",	zh:"語表十法聚",is:"#cittajakalapa#10kalapa",has:"#vacivinnatti#sadda",en:"vocal intimation nonad kalapa",pli:"vacīviññatti dasaka"},
{id:"lahutadi11",	zh:"色輕快性十一法聚",is:"#cittajakalapa#utujakalapa#aharajakalapa#11kalapa",has:"#rupassalahuta#rupassamuduta#rupassakammannata",en:"lightness un-decad kalapa",pli:"lahutā ekādasaka"},


{id:"kayavinnatti12",	zh:"身表色輕快性十二法聚",is:"#cittajakalapa#12kalapa",has:"#kayavinnatti#rupassalahuta#rupassamuduta#rupassakammannata",en:"bodily intimation and lightness triad dodecad kalapa",pli:"kāyaviññatti dvidasaka"},
{id:"vacivinnatti13",	zh:"語表色輕快性十三法聚",is:"#cittajakalapa#13kalapa",has:"#vacivinnatti#sadda#rupassalahuta#rupassamuduta#rupassakammannata",en:"vocal intimation and lightness triad tridecad kalapa",pli:"vacīviññatti navaka"},

{id:"sadda9",	zh:"入出息心生聲九法聚",is:"#cittajakalapa#9kalapa",has:"#sadda",en:"anapana mind born sound nonad kalapa",pli:"assāsa passāsa cittaja sadda navaka",source:"智慧之光四版pg108"},

{id:"sadda12",	zh:"入出息心生聲色輕快十二法聚",is:"#cittajakalapa#12kalapa",has:"#sadda#rupassalahuta#rupassamuduta#rupassakammannata",en:"anapana mind born sound nonad kalapa",pli:"assāsa passāsa cittaja sadda dvidasaka",source:"智慧之光四版pg108"},

{id:"utuja8",	zh:"時節生純八法聚",is:"#utujakalapa#8kalapa",en:"temperature born pure octad kalapa",pli:"utuja suddhaṭṭhaka"},

{id:"utujasadda9",	zh:"時節生聲九法聚",is:"#utujakalapa#9kalapa",has:"#sadda",en:"temperature born sound nonad kalapa",pli:"utuja sadda navaka",source:"智慧之光四版pg108"},
{id:"utujasadda12",	zh:"聲色輕快十二法聚",is:"#utujakalapa#12kalapa",has:"#sadda#rupassalahuta#rupassamuduta#rupassakammannata",en:"temperature born sound dodecad kalapa",pli:"saddaa lahutā dvidasaka",source:"智慧之光四版pg108"},

{id:"aharaja8",	zh:"食生純八法聚",is:"#aharajakalapa#8kalapa",en:"nutriment born pure octad kalapa",pli:"aharaja suddhaṭṭhaka"},
{id:"catassoyoniyo",zh:"四種出生",is:"#jati",has:"#jalabuja#andaja#samsedaja#opapatika",en:"4 kinds of birth",pli:"catasso yoniyo"},
{id:"jalabuja",zh:"胎生",en:"womb-born",pli:"jalābuja"},
{id:"andaja",zh:"卵生",en:"womb-born",pli:"aṇḍaja"},
{id:"samsedaja",zh:"濕生",en:"moisture-born",pli:"saṃsedajā"},
{id:"opapatika",zh:"化生",en:"spontaneous-born",pli:"opapātikā"},

//十結 pg263 
//八正道 269
//275四念住四正勤四神足五根五力菩提分

//十二處，十八界


{id:"32partofbody",zh:"32身分",en:"32 parts of body",has:"#20earth#12water"},
{id:"20earth",zh:"20地界身分",has:"#kesa#loma#nakha#danta#taco#mamsa#naharu#atthi#atthiminja#vakka#hadaya#yakana#kilomaka#pihaka#papphasa#anta#antaguna#udariya#karasa#matthalunga"},
{id:"kesa",zh:"頭髮",en:"head hair",pli:"kesā"},
{id:"loma",zh:"身毛",en:"body hair",pli:"lomā"},
{id:"nakha",zh:"指甲",en:"nail",pli:"nakhā"},
{id:"danta",zh:"牙齒",en:"teeth",pli:"dantā"},
{id:"taco",zh:"皮膚",en:"skin",pli:"taco"},
{id:"mamsa",zh:"肉",en:"flesh",pli:"maṃsa"},
{id:"naharu",zh:"腱",en:"sinews",pli:"nahāru"},
{id:"atthi",zh:"骨",en:"bones",pli:"aṭṭhi"},
{id:"atthiminja",zh:"骨髓",en:"marrow",pli:"aṭṭhimiñja"},
{id:"vakka",zh:"腎",en:"kidney",pli:"vakka"},
{id:"hadaya",zh:"心臟",en:"heart",pli:"hadaya"},
{id:"yakana",zh:"肝",en:"liver",pli:"yakana"},
{id:"kilomaka",zh:"膜",en:"membrane",pli:"kilomaka"},
{id:"pihaka",zh:"脾",en:"spleen",pli:"pihaka"},
{id:"papphasa",zh:"肺",en:"lungs",pli:"papphasa"},
{id:"anta",zh:"腸",en:"intestines",pli:"anta"},
{id:"antaguna",zh:"腸間膜",en:"mesentery",pli:"antaguṇa"},
{id:"udariya",zh:"胃",en:"gorge",pli:"udariya"},
{id:"karasa",zh:"糞",en:"faeces",pli:"karāsa"},
{id:"matthalunga",zh:"腦",en:"brain",pli:"matthaluṅga"},
{id:"12water",zh:"12水界身分",has:"#pitta#semha#pubbo#lohita#sedo#medo#assu#vasa#khelo#singhanika#lasika#mutta"},
{id:"pitta",zh:"膽汁",en:"bile",pli:"pitta"},
{id:"semha",zh:"痰",en:"phlegm",pli:"semha"},
{id:"pubbo",zh:"膿",en:"pus",pli:"pubbo"},
{id:"lohita",zh:"血",en:"blood",pli:"lohita"},
{id:"sedo",zh:"汗",en:"sweat",pli:"sedo"},
{id:"medo",zh:"脂肪",en:"fat",pli:"medo"},
{id:"assu",zh:"淚",en:"tear",pli:"assu"},
{id:"vasa",zh:"脂膏",en:"grease",pli:"vasā"},
{id:"khelo",zh:"唾",en:"siliva",pli:"kheḷo"},
{id:"singhanika",zh:"涕",en:"snot",pli:"siṅghānika"},
{id:"lasika",zh:"關節滑液",en:"synovia",pli:"lasikā"},
{id:"mutta",zh:"尿",en:"urine",pli:"mutta"},

//過去五因	現在五果 現在五因 未來五果

{id:"3vatta",zh:"三輪轉",types:"#kilesavatta#kammavatta#vipakavatta",en:"three rounds",pli:"vaṭṭa"},
{id:"kilesavatta",zh:"煩惱輪",has:"#avijja#tanha#upadana",en:"round of defilements",pli:"kilesavaṭṭa"},
{id:"kammavatta",zh:"業輪",has:"#kammabhava#sankhara",en:"round of kamma",pli:"kammavaṭṭa"},
{id:"kammabhava",zh:"業有",en:"kammic existence",pli:"kammabhava",stem:"#kamma#bhava"},
{id:"vipakavatta",zh:"果報輪",has:"#jati#vinnana#namarupa#salayatana#phassa#vedana",en:"round of results",pli:"vipākavaṭṭa"},

//發趣法

{id:"patthana",zh:"發趣",types:"#3patthana#24paccayo",en:"patthana",pli:"paṭṭhāna"},


{id:"paccaya",zh:"緣",en:"condition",pli:"paccaya"},


{id:"24paccayo",zh:"24緣",en:"24 conditions",types:"#6paccayo",pli:"24 paccayo"
,has:"#hetupaccayo#arammanapaccayo#adhipatipaccayo#anantarapaccayo#samanantarapaccayo#sahajatapaccayo#annamannapaccayo#nissayapaccayo#upanissayapaccayo#purejatapaccayo#pacchajatapaccayo#asevanapaccayo#kammapaccayo#vipakapaccayo#aharapaccayo#indriyapaccayo#jhanapaccayo#maggapaccayo#sampayuttapaccayo#vippayuttapaccayo#atthipaccayo#natthipaccayo#vigatapaccayo#avigatapaccayo",stem:"#paccaya"},
//def from 表解 12 章五十二種緣〈簡表〉 簡表
{id:"hetupaccayo",zh:"因緣",def:"【因】對同一名聚裡的〔其餘名法〕及對〔俱生色聚〕",en:"root condition",pli:"hetupaccayo"},
{id:"arammanapaccayo",zh:"所緣緣",def:"【任何對象或目標】對〔名聚〕",en:"object condition",pli:"ārammaṇapaccayo"},

{id:"arammana",zh:"所緣",en:"object",pli:"ārammaṇa"},
{id:"vatthu",zh:"依處",en:"base",pli:"vatthu"},


{id:"adhipatipaccayo",zh:"增上緣",has:"#sahajataradhipatipaccayo#arammanadhipatipaccayo",en:"predominance condition",pli:"adhipatipaccayo"},
{id:"sahajataradhipatipaccayo",zh:"俱生增上緣",def:"【#4adhipati;】對同一名聚裡的〔其餘名法〕及對〔心生色聚〕}",en:"",pli:""},
{id:"arammanadhipatipaccayo",zh:"所緣增上緣",def:"【所緣】對〔名聚〕",en:"",pli:""},
{id:"4adhipati",zh:"四增上",syn:"4iddhipada",en:"4 predominances",pli:"cattāro-adhipatī"},

{id:"anantarapaccayo",zh:"無間緣",def:"【前一名聚】對〔後一名聚〕",en:"proximate condition",pli:"anantarapaccayo"},
{id:"samanantarapaccayo",zh:"相續緣",def:"【前一名聚】對〔後一名聚〕",en:"contiguity condition",pli:"samanantarapaccayo"},
{id:"sahajatapaccayo",zh:"俱生緣",en:"conascence condition",pli:"sahajātapaccayo"},
{id:"annamannapaccayo",zh:"相互緣",en:"mutuality condition",pli:"aññamaññapaccayo"},
{id:"nissayapaccayo",zh:"依止緣",en:"support condition",pli:"nissayapaccayo"},
{id:"upanissayapaccayo",zh:"親依止緣",en:"decisive support condition",pli:"upanissayapaccayo"},
{id:"purejatapaccayo",zh:"前生緣",en:"prenascence condition",pli:"purejātapaccayo"},
{id:"pacchajatapaccayo",zh:"後生緣",def:"【後生名聚】對色身的〔前生色聚〕",en:"postnascence condition",pli:"pacchajātapaccayo"},
{id:"asevanapaccayo",zh:"重覆緣",def:"【前一速行名聚】對〔後一速行名聚〕",en:"repetition condition",pli:"āsevanapaccayo"},
{id:"kammapaccayo",zh:"業緣",en:"kamma condition",pli:"kammapaccayo",stem:"#kamma"},
{id:"kamma",	zh:"業",en:"kamma",pli:"kamma"},
{id:"vipakapaccayo",zh:"果報緣",def:"同一果報名聚裡的【名法】與〔其餘名法〕及對〔俱生色聚〕",en:"result condition",pli:"vipakapaccayo",stem:"#vipaka"},
{id:"vipaka",zh:"果報|異熟",en:"resultant",pli:"vipāka"},
{id:"aharapaccayo",zh:"食緣",en:"nutriment condition",pli:"āhārapaccayo",stem:"#ahara"},
{id:"indriyapaccayo",zh:"根緣",en:"faculty condition",pli:"indriyapaccayo",stem:"#indriya"},
{id:"jhanapaccayo",zh:"禪那緣",def:"【禪支】對同一名聚裡的〔其餘名法〕及對〔俱生色聚〕",en:"jhana condition",pli:"jhānapaccayo",stem:"#jhana"},
{id:"maggapaccayo",zh:"道緣",def:"【道支】對同一名聚裡的〔其餘名法〕及對〔俱生色聚〕",en:"path condition",pli:"maggapaccayo",stem:"#magga"},
{id:"sampayuttapaccayo",zh:"相應緣",def:"同一名聚裡的【名法】與〔其餘名法〕相互之間",stem:"#sampayutta",en:"associated condition",pli:"sampayuttapaccayo"},
{id:"vippayuttapaccayo",zh:"不相應緣",stem:"#vippayutta",en:"dissociated condition",pli:"vippayuttapaccayo"},
{id:"sampayutta",zh:"相應",en:"associated",pli:"sampayutta"},
{id:"vippayutta",zh:"不相應",en:"dissociated",pli:"vippayutta"},

{id:"atthipaccayo",zh:"有緣",en:"presence condition",pli:"sampayuttapaccayo"},
{id:"natthipaccayo",zh:"無有緣",def:"【前一名聚】對〔後一名聚〕",en:"absence condition",pli:"vippayuttapaccayo"},
{id:"vigatapaccayo",zh:"離去緣",def:"【前一名聚】對〔後一名聚〕",en:"disappearance condition",pli:"sampayutta"},
{id:"avigatapaccayo",zh:"不離去緣",en:"non-disappearance condition",pli:"vippayutta"},

{id:"3patthana",zh:"發趣三要",has:"#paccayadhamma#paccayuppannadhamma#paccayasatti",en:"3 factors of patthana"},

{id:"paccayadhamma",zh:"緣法",en:"conditioning states",pli:"paccayadhammā",has:"#p_rupa#p_nama#p_rupa"},
{id:"paccayuppannadhamma",zh:"緣生法",en:"conditionally arisen states",pli:"paccayuppannadhammā",has:"#pu_rupa#pu_nama#pu_rupa"},
{id:"paccayasatti",zh:"緣力",en:"conditioning force of the condition",pli:"paccayasatti"},

{id:"6paccayo",zh:"六組緣",source:"阿耨樓陀尊者",en:"6 fold conditions",pli:"chakka paccaya",has:"#p_nn#p_nnr#p_nr#p_rn#p_nrn#p_nrnr"},

{id:"p_nama",zh:"緣法名法",en:"conditioning mentality",pli:"paccayanāmadhammā",stem:"#nama"},
{id:"p_rupa",zh:"緣法色法",en:"conditioning material phenomena",pli:"paccayarūpadhammā",stem:"#rupa"},
{id:"p_namarupa",zh:"緣法名色",en:"conditioning mentality and material phenomena",pli:"paccayanāmarūpadhammā",stem:"#namarupa"},
{id:"pu_nama",zh:"緣生名法",en:"conditionally arisen mentality",pli:"paccayuppannanāmadhammā"},
{id:"pu_rupa",zh:"緣生色法",en:"conditionally arisen material phenomena",pli:"paccayuppannarūpadhammā"},
{id:"pu_namarupa",zh:"緣生名色",en:"conditionally arisen mentality and material phenomena",pli:"paccayuppannanāmarūpadhammā"},

{id:"p_nn",zh:"名→名",def:" #p_nama;→ #pu_nama;",has:"#anantarapaccayo#samanantarapaccayo#asevanapaccayo#sampayuttapaccayo#natthipaccayo#vigatapaccayo",en:"nama→nama",pli:"nāma→nāma"},
{id:"p_nnr",zh:"名→名色",def:" #p_nama;→ #pu_namarupa;",has:"#hetupaccayo#kammapaccayo#vipakapaccayo#jhanapaccayo#maggapaccayo",en:"nama→namarupa",pli:"nāma→nāmarūpa"},
{id:"p_nr",zh:"名→色",def:" #p_nama;→ #pu_rupa;",has:"#pacchajatapaccayo",en:"nama→rupa",pli:"nāma→rūpa"},
{id:"p_rn",zh:"色→名",def:" #p_rupa;→ #pu_nama;",has:"#purejatapaccayo",en:"rupa→nama",pli:"rūpa→nāma"},
{id:"p_nrn",zh:"名色→名",def:" #p_namarupa;→ #pu_nama;",has:"#arammanapaccayo#upanissayapaccayo",en:"namarupa→nama",pli:"nāmarūpa→nāma"},
{id:"p_nrnr",zh:"名色→名色",def:" #p_namarupa;→ #pu_namarupa;",has:"#adhipatipaccayo#sahajatapaccayo#annamannapaccayo#nissayapaccayo#aharapaccayo#indriyapaccayo#vippayuttapaccayo#atthipaccayo#avigatapaccayo",en:"namarupa→namarupa",pli:"nāmarūpa→nāmarūpa"},

]
	if (typeof module!=="undefined") {
		module.exports=coreset;
	} else {
		window.rawdataset.push(coreset);
	}
})();